
import { createClient } from 'jsr:@supabase/supabase-js@2'

const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

Deno.serve(async (req) => {
    if (req.method === 'OPTIONS') {
        return new Response('ok', { headers: corsHeaders })
    }

    const url = new URL(req.url)
    const family = url.searchParams.get('family')
    const weightsParam = url.searchParams.get('weights')
    const variableParam = url.searchParams.get('variable')

    if (!family) {
        return new Response('Missing family parameter', { status: 400, headers: corsHeaders })
    }

    // Parse weights
    const requestedWeights = weightsParam ? weightsParam.split(',').map(w => parseInt(w.trim())) : []
    const preferVariable = variableParam === 'true'

    try {
        const supabaseClient = createClient(
            Deno.env.get('SUPABASE_URL') ?? '',
            Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
        )

        // 1. Fetch Font Data
        // Search by slug (exact match) OR name (case-insensitive)
        const { data: fonts, error: fontError } = await supabaseClient
            .from('fonts')
            .select('*, font_variants(*)')
            .or(`slug.eq.${family},name.ilike.${family}`)
            .order('created_at', { ascending: false })
            .limit(1)

        if (fontError || !fonts || fonts.length === 0) {
            console.error('Font fetch error:', fontError)
            return new Response('Font not found', { status: 404, headers: corsHeaders })
        }

        const font = fonts[0]

        let css = `/* Font: ${font.name} */\n/* Generated by NoBadFonts */\n\n`

        // Helper map variant name to weight/style
        const parseVariant = (name: string) => {
            const lower = name.toLowerCase()
            let weight = 400
            let style = 'normal'

            if (lower.includes('thin')) weight = 100
            if (lower.includes('extra light') || lower.includes('extralight')) weight = 200
            if (lower.includes('light') && weight === 400) weight = 300 // default but check if not overridden
            if (lower.includes('medium')) weight = 500
            if (lower.includes('semi bold') || lower.includes('semibold')) weight = 600
            if (lower.includes('bold') && weight === 400) weight = 700
            if (lower.includes('extra bold') || lower.includes('extrabold')) weight = 800
            if (lower.includes('black')) weight = 900

            if (lower.includes('italic')) style = 'italic'

            return { weight, style }
        }

        // 2. Process Variants
        // Filter variants based on requested weights if provided
        const variants = font.font_variants || []

        // Check for "Variable" variant if requested
        // Naive check: if name contains "Variable"
        const variableVariant = variants.find((v: any) => v.variant_name.toLowerCase().includes('variable'))

        if (preferVariable && variableVariant) {
            // Serve variable font
            const url = variableVariant.woff2_url || variableVariant.woff_url || variableVariant.ttf_url
            if (url) {
                css += `@font-face {
  font-family: '${font.name}';
  src: url('${url}') format('woff2-variations');
  font-weight: 100 900;
  font-style: normal;
  font-display: swap;
}\n\n`
            }
        }

        // Build static variants CSS
        // Even if variable is requested, we might want to fallback or serve static too if variable logic fails?
        // For now, if variable served, stop? Or serve both? Usually one is enough.
        // Let's standardise: if preferVariable is true AND we found one, return ONLY that.

        if (!preferVariable || !variableVariant) {
            variants.forEach((v: any) => {
                const { weight, style } = parseVariant(v.variant_name)

                // Check if this variant matches requested weights (if any specified)
                // If weights are requested, only include matching weights
                if (requestedWeights.length > 0 && !requestedWeights.includes(weight)) {
                    return
                }

                // Fallback Logic: WOFF2 > WOFF > TTF > OTF
                let fileUrl = v.woff2_url
                let format = 'woff2'

                if (!fileUrl) {
                    fileUrl = v.woff_url
                    format = 'woff'
                }
                if (!fileUrl) {
                    fileUrl = v.ttf_url
                    format = 'truetype'
                }
                if (!fileUrl) {
                    fileUrl = v.otf_url
                    format = 'opentype'
                }

                if (fileUrl) {
                    css += `@font-face {
  font-family: '${font.name}';
  src: url('${fileUrl}') format('${format}');
  font-weight: ${weight};
  font-style: ${style};
  font-display: swap;
}\n\n`
                }
            })

            // Detailed fallback for Legacy Main Files (no variants)
            if (variants.length === 0) {
                let fileUrl = font.woff2_url
                let format = 'woff2'
                if (!fileUrl) { fileUrl = font.woff_url; format = 'woff'; }
                if (!fileUrl) { fileUrl = font.ttf_url; format = 'truetype'; }
                if (!fileUrl) { fileUrl = font.otf_url; format = 'opentype'; }

                if (fileUrl) {
                    css += `@font-face {
      font-family: '${font.name}';
      src: url('${fileUrl}') format('${format}');
      font-weight: 400;
      font-style: normal;
      font-display: swap;
    }\n`
                }
            }
        }

        return new Response(css, {
            headers: {
                ...corsHeaders,
                'Content-Type': 'text/css; charset=utf-8',
                'Cache-Control': 'public, max-age=31536000, immutable',
            },
        })

    } catch (error) {
        console.error('Error:', error)
        return new Response('Internal Server Error', { status: 500, headers: corsHeaders })
    }
})
